### ISSUE TITLE
Error in plot.go: undefined: chart.StyleShow

### ISSUE THREAD

**Issue by jingwenw** [jonpchin/gochess#100]
Error in the function name?

# github.com/jonpchin/gochess/gostuff
../../go/src/github.com/jonpchin/gochess/gostuff/plot.go:104:15: undefined: chart.StyleShow
../../go/src/github.com/jonpchin/gochess/gostuff/plot.go:105:15: undefined: chart.StyleShow
../../go/src/github.com/jonpchin/gochess/gostuff/plot.go:109:15: undefined: chart.StyleShow
../../go/src/github.com/jonpchin/gochess/gostuff/plot.go:110:15: undefined: chart.StyleShow
james@ip-172-31-29-166:~/myRepos/gochess$ emacs ../../go/src/github.com/jonpchin/gochess/gostuff/plot.go

Thanks,
James

**Comment by jonpchin** [comment]
This is because https://github.com/wcharczuk/go-chart updated their repo and their change is not backwards compatible and it broke something in this repo.

**Comment by jingwenw** [comment]
Thanks for the response.
